spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lozanotalavera/online-store.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t

server:
  port: 8081